config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :scores
  resources :games
  resources :players
  resources :admins

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # Defines the root path route ("/")
  root "games#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/game.rb
class Game < ApplicationRecord
  validates :game_name, presence: true
  validates :p1, presence: true
  validates :p2, presence: true
  validates :p3, presence: true
  validates :p4, presence: true

  validate :check_different_players

  def check_different_players
    players = [p1, p2, p3, p4]
    len = players.length
    for i in 1..len do
      for j in 1..len do
        if i != j && players[i] == players[j]
          err_s = "must be unique to others"
          errors.add(:p1, err_s) if i = 1
          errors.add(:p2, err_s) if i = 2
          errors.add(:p3, err_s) if i = 3
          errors.add(:p4, err_s) if i = 4
          return
        end
      end
    end
  end

end

app/models/minigame.rb
class Minigame < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
  validates :player_name, presence: true
end

app/models/score.rb
class Score < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
    @players = Player.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    @games = Game.all
  end

  def show
    @game = Game.find(params[:id])
    @scores = Score.where(game_id: @game.id)
    @p1 = @game.p1
    @p2 = @game.p2
    @p3 = @game.p3
    @p4 = @game.p4
  end

  def new
    @game = Game.new
    @players = Player.all
  end

  def create
    @game = Game.new(game_params)

    if @game.save
      @id = @game.id
      for i in 1..28
        Score.new(game_id: @id, score_position: i, value_p1: 0, value_p2: 0, value_p3: 0, value_p4: 0).save
      end
        Minigame.new(game_id: @id, player_id: @game.p1).save
        Minigame.new(game_id: @id, player_id: @game.p2).save
        Minigame.new(game_id: @id, player_id: @game.p3).save
        Minigame.new(game_id: @id, player_id: @game.p4).save
      redirect_to @game
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
    @game = Game.find(params[:id])

    if @game.update(game_params)
      redirect_to @game
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def game_params
      params.require(:game).permit(:game_name, :p1, :p2, :p3, :p4)
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def new
    @player = Player.new
  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to admins_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
    def player_params
      params.require(:player).permit(:player_name, :games_played, :wins)
    end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def update
    @score = Score.find(params[:id])

    @score.update(score_params)
  end

  private
    def score_params
      params.require(:score).permit(:value_p1, :value_p2, :value_p3, :value_p4)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/admins/index.html.erb
<%= link_to "<- home", root_path %>

<h1>Admin page</h1>

<h2>Players:</h2>
<%= link_to "add player", new_player_path%>
<ul>
  <% @players.each do |player| %>
    <% entry = player.id.to_s + "_" + player.player_name %> 
    <% entry = "0" + entry if player.id < 10 %>
    <li><%= entry %></li>
  <% end %>
</ul>

app/views/games/_form.html.erb
<%= form_with model: @game do |form| %>
  <div>
    <%= form.label :game_name %><br>
    <%= form.text_field :game_name %>
    <% @game.errors.full_messages_for(:game_name).each do |message| %>
      <div><%= message %></div>
      <br>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.label :p1 %>
    <%= form.select :p1, Player.order(:player_name).map { |player| [player.player_name, player.id] } %>
    <% @game.errors.full_messages_for(:p1).each do |message| %>
      <div><%= message %></div>
      <br>
    <% end %>
  </div>

  <div>
    <%= form.label :p2 %>
    <%= form.select :p2, Player.order(:player_name).map { |player| [player.player_name, player.id] } %>
    <% @game.errors.full_messages_for(:p2).each do |message| %>
      <div><%= message %></div>
      <br>
    <% end %>
  </div>

  <div>
    <%= form.label :p3 %>
    <%= form.select :p3, Player.order(:player_name).map { |player| [player.player_name, player.id] } %>
    <% @game.errors.full_messages_for(:p3).each do |message| %>
      <div><%= message %></div>
      <br>
    <% end %>
  </div>

  <div>
    <%= form.label :p4 %>
    <%= form.select :p4, Player.order(:player_name).map { |player| [player.player_name, player.id] } %>
    <% @game.errors.full_messages_for(:p4).each do |message| %>
      <div><%= message %></div>
      <br>
    <% end %>
  </div>

  <br>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Edit game</h1>

<%= render "form", article: @article %>

app/views/games/index.html.erb
  <h1>Games:</h1>

  <%= link_to "New Game", new_game_path %>

  <ul>
    <% @games.each do |game| %>
      <li>
        <%= link_to game.game_name, game %>
      </li>
    <% end %>
  </ul>

  <%= link_to "admin", admins_path %>

app/views/games/new.html.erb
<%= link_to "<- home", root_path %>

<h1>Create new game</h1>

<%= render "form", game: @game %>

app/views/games/show.html.erb
<%= link_to "<- home", root_path %>

<h1>
  <%= @game.game_name %>
</h1>

<table> <%# SCORES %>
  <tr>
    <th><%= Player.find(@game.p1).player_name %></th>
    <th><%= Player.find(@game.p2).player_name %></th>
    <th><%= Player.find(@game.p3).player_name %></th>
    <th><%= Player.find(@game.p4).player_name %></th>
  </tr>

  <% for i in 1..28 %>
    <%= form_with model: Score.where(game_id: @game.id, score_position: i).first do |form| %>
      <tr>
        <td><%= form.number_field :value_p1, in: -8..32, step: 1 %></td>
        <td><%= form.number_field :value_p2, in: -8..32, step: 1 %></td>
        <td><%= form.number_field :value_p3, in: -8..32, step: 1 %></td>
        <td><%= form.number_field :value_p4, in: -8..32, step: 1 %></td>
        <td><%= form.submit %></td>
      </tr>
    <% end %>
  <% end %>

  <tr>
    <td>total: <%= @scores.sum(:value_p1) %></td>
    <td>total: <%= @scores.sum(:value_p2) %></td>
    <td>total: <%= @scores.sum(:value_p3) %></td>
    <td>total: <%= @scores.sum(:value_p4) %></td>
  </tr>
</table>

<br>

<table> <%# GAMES %>
  <tr>
    <th>Game</th>
    <th>Name 1</th>
    <th>Name 2</th>
    <th>Name 3</th>
    <th>Name 4</th>
  </tr>
  <% games = ["min", "max", "src", "dam", "krl", "lor", "pro"] %>
  <% games.each do |game| %>
    <tr>
      <td><%= game %></td>
      <% 4.times do %>
        <td><button></button></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br>

<button>SAVE</button>

<ul>
  <li><%= link_to "Edit", edit_game_path(@game) %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Lora Scorekeeper" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/players/new.html.erb
<%= link_to "<- back", admins_path %>

<h1>Create player:</h1>

<%= form_with model: @player do |form| %>

  <div>
    <%= form.label :player_name %><br>
    <%= form.text_field :player_name %>
    <% @player.errors.full_messages_for(:player_name).each do |msg| %>
      <p><%= msg %></p>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/show.html.erb
<h1>HELLO, WORLD!!!</h1>
<p>name of game</p>
<input type="text">
<br>
<p>player 1:</p>
<input type="text">
<br>
<p>player 2:</p>
<input type="text">
<br>
<p>player 3:</p>
<input type="text">
<br>
<p>player 4:</p>
<input type="text">
<br>
<button>new game</button>
<table> <%# SCORES %>
  <tr>
    <th>Name 1</th>
    <th>Name 2</th>
    <th>Name 3</th>
    <th>Name 4</th>
  </tr>
  <% 28.times do %>
    <tr>
      <% 4.times do %>
        <td><input type="number" min=-224 max=224 value=0></td>
      <% end %>
    </tr>
  <% end %>
  <tr>
    <% 4.times do %>
      <td>total: x</td>
    <% end %>
  </tr>
</table>

<br>

<table> <%# GAMES %>
  <tr>
    <th>Game</th>
    <th>Name 1</th>
    <th>Name 2</th>
    <th>Name 3</th>
    <th>Name 4</th>
  </tr>
  <% games = ["min", "max", "src", "dam", "krl", "lor", "pro"] %>
  <% games.each do |game| %>
    <tr>
      <td><%= game %></td>
      <% 4.times do %>
        <td><button></button></td>
      <% end %>
    </tr>
  <% end %>
</table>

<br>

<button>SAVE</button>